import { test, describe, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { Writer } from "../src/fs/write.mjs";
import { wireStyleImports, wireLayerOrder, patchJson } from "../src/css/tokens/wire.mjs";

/**
 * Generated stylesheets and data files do nothing until something references
 * them. Every failure here is silent — the files look correct on disk and have
 * no effect on the built site — which is exactly why they need tests.
 */

let root;
let writer;

beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), "mig-wire-"));
  writer = new Writer({ targetRoot: root, artifactsDir: path.join(root, ".migration") });
});

afterEach(() => fs.rmSync(root, { recursive: true, force: true }));

const write = (rel, content) => {
  const full = path.join(root, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, "utf8");
  return full;
};

const read = (rel) => fs.readFileSync(path.join(root, rel), "utf8");

describe("style imports", () => {
  test("imports whatever was generated, detected from disk", () => {
    // Passing the caller's idea of what exists means a file generated by a
    // different command is never imported — it just sits there doing nothing.
    write("src/styles/style.pcss", '@import "_base.pcss";\n');
    write("src/styles/source/_tokens.pcss", ":root {}");
    write("src/styles/source/_chrome.pcss", "footer {}");

    const result = wireStyleImports(writer, root, "src/styles");
    assert.equal(result.ok, true);

    const entry = read("src/styles/style.pcss");
    assert.match(entry, /@import "source\/_tokens\.pcss";/);
    assert.match(entry, /@import "source\/_chrome\.pcss";/);
    assert.match(entry, /@import "_base\.pcss";/, "existing imports survive");
  });

  test("imports the source theme after the template's own styles", () => {
    write("src/styles/style.pcss", '@import "_base.pcss";\n');
    write("src/styles/source/_tokens.pcss", ":root {}");

    wireStyleImports(writer, root, "src/styles");
    const entry = read("src/styles/style.pcss");
    assert.ok(
      entry.indexOf("_base.pcss") < entry.indexOf("source/_tokens.pcss"),
      "the source theme must come last to override the template's variables"
    );
  });

  test("is idempotent", () => {
    write("src/styles/style.pcss", '@import "_base.pcss";\n');
    write("src/styles/source/_tokens.pcss", ":root {}");

    wireStyleImports(writer, root, "src/styles");
    const once = read("src/styles/style.pcss");
    wireStyleImports(writer, root, "src/styles");

    assert.equal(read("src/styles/style.pcss"), once);
    assert.equal((once.match(/mig:begin source-theme-imports/g) || []).length, 1);
  });

  test("reports a missing entry point rather than failing silently", () => {
    const result = wireStyleImports(writer, root, "src/styles");
    assert.equal(result.ok, false);
    assert.match(result.reason, /not found/);
  });

  test("reports when there is nothing generated to import", () => {
    write("src/styles/style.pcss", "@import \"_base.pcss\";\n");
    const result = wireStyleImports(writer, root, "src/styles");
    assert.equal(result.ok, false);
  });
});

describe("cascade layer order", () => {
  const LAYOUT = "src/layouts/BaseLayout.astro";

  test("inserts the source layers in the right places", () => {
    write(LAYOUT, "<style>@layer reset, base, components, page-sections, utils, overrides;</style>");

    const result = wireLayerOrder(writer, root, LAYOUT);
    assert.equal(result.ok, true);

    // `source-base` beats the template's base but never a component;
    // `source-bridge` can restyle components but not utilities.
    assert.deepEqual(result.layers, [
      "reset",
      "base",
      "source-base",
      "components",
      "page-sections",
      "source-bridge",
      "utils",
      "overrides",
    ]);
    assert.match(read(LAYOUT), /@layer reset, base, source-base, components/);
  });

  test("is idempotent", () => {
    write(LAYOUT, "<style>@layer reset, base, components, page-sections, utils, overrides;</style>");
    wireLayerOrder(writer, root, LAYOUT);
    const once = read(LAYOUT);
    wireLayerOrder(writer, root, LAYOUT);
    assert.equal(read(LAYOUT), once);
  });

  test("reports a layout with no layer declaration", () => {
    write(LAYOUT, "<html></html>");
    const result = wireLayerOrder(writer, root, LAYOUT);
    assert.equal(result.ok, false);
    assert.match(result.reason, /no @layer declaration/);
  });
});

describe("data file patching", () => {
  const BRANDING = "src/data/branding.json";

  test("replaces the template's stand-in values", () => {
    // A starter ships vivid placeholders; treating them as deliberate leaves
    // the extracted palette correct in the file and absent from the site.
    write(BRANDING, JSON.stringify({ colorBrand: "#ff0000", colorLink: "blue" }, null, 2));

    patchJson(writer, root, BRANDING, { colorBrand: "#134545", colorLink: "#751414" });

    const data = JSON.parse(read(BRANDING));
    assert.equal(data.colorBrand, "#134545");
    assert.equal(data.colorLink, "#751414");
  });

  test("keeps a value the operator actually chose", () => {
    write(BRANDING, JSON.stringify({ colorBrand: "#2b5f5f" }, null, 2));
    patchJson(writer, root, BRANDING, { colorBrand: "#134545" });
    assert.equal(JSON.parse(read(BRANDING)).colorBrand, "#2b5f5f");
  });

  test("replaces keys the source is authoritative for", () => {
    // A font link for typefaces this site never uses is wrong, not a preference.
    write(BRANDING, JSON.stringify({ fontLinks: ["https://fonts.example/playfair"] }, null, 2));

    patchJson(writer, root, BRANDING, { fontLinks: ["https://use.typekit.net/x.css"] }, {
      replaceKeys: ["fontLinks"],
    });

    assert.deepEqual(JSON.parse(read(BRANDING)).fontLinks, ["https://use.typekit.net/x.css"]);
  });

  test("fills an empty value", () => {
    write(BRANDING, JSON.stringify({ colorBrandSubtle: "", extraColors: [] }, null, 2));
    patchJson(writer, root, BRANDING, { colorBrandSubtle: "#d0c8b7" });
    assert.equal(JSON.parse(read(BRANDING)).colorBrandSubtle, "#d0c8b7");
  });

  test("leaves untouched keys alone", () => {
    write(BRANDING, JSON.stringify({ colorBrand: "#ff0000", custom: "keep me" }, null, 2));
    patchJson(writer, root, BRANDING, { colorBrand: "#134545" });
    assert.equal(JSON.parse(read(BRANDING)).custom, "keep me");
  });

  test("reports a missing file rather than creating one", () => {
    const result = patchJson(writer, root, BRANDING, { colorBrand: "#134545" });
    assert.equal(result.ok, false);
  });
});
