import { chromium } from "playwright";
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await c.newPage();
const [url, out, label] = process.argv.slice(2);
await p.goto(url, { waitUntil: "networkidle", timeout: 60000 });
await p.waitForTimeout(1500);
const scope = process.argv[5] || "body";
const link = p.locator(`${scope} a:has-text("${label}")`).first();
await link.hover();
await p.waitForTimeout(1200);
await p.screenshot({ path: `${out}/drop-${label.replace(/\s+/g,'-')}.png`, clip: { x: 0, y: 0, width: 1440, height: 620 } });
console.log("captured", label);
await b.close();
