import { chromium } from "playwright";
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1440, height: 900 } });
const p = await c.newPage();
const [url, out] = process.argv.slice(2);
await p.goto(url, { waitUntil: "networkidle", timeout: 60000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${out}/head-top.png`, clip: { x: 0, y: 0, width: 1440, height: 180 } });
console.log("captured top");
await b.close();
