import { chromium } from "playwright";
const b=await chromium.launch(); const p=await b.newPage({viewport:{width:1440,height:1000}});
await p.goto(process.argv[2],{waitUntil:"networkidle"}); await p.waitForTimeout(1500);
await p.evaluate(async()=>{await new Promise(r=>{let y=0;const t=setInterval(()=>{window.scrollTo(0,y);y+=800;
  if(y>document.body.scrollHeight){clearInterval(t);window.scrollTo(0,0);r();}},40);});});
await p.waitForTimeout(600);
const el=await p.$(process.argv[3]);
if(el) await el.screenshot({path:process.argv[4]});
else console.log("selector not found");
await b.close();
